// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using System.Collections.Generic;
using UIKit;

namespace PhoneWordiOS
{
	public partial class CallHistoryController : UIViewController
	{
        static NSString MyCellId = new NSString("MyCellId");
        public CallHistoryController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var db = new Core.DB.DatabaseManager(new DB.PathManager());
            var phoneNumbers = db.GetAllData<Core.Models.PhoneNumber>();
            callHistoryTableView.Source = new TableViewSource(phoneNumbers.Value, this);
        }

        public class TableViewSource : UITableViewSource
        {
            List<Core.Models.PhoneNumber> tabledata;
            CallHistoryController owner;
            public TableViewSource(List<Core.Models.PhoneNumber> items, CallHistoryController owner)
            {
                tabledata = items;
                this.owner = owner;
            }
            public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
            {
                UITableViewCell cell = tableView.DequeueReusableCell("cell");
                if (cell == null)
                {
                    cell = new UITableViewCell(UITableViewCellStyle.Default, "cell");
                }
                cell.TextLabel.Text = tabledata[indexPath.Row].phoneNumber;
                return cell;
            }
            public override nint RowsInSection(UITableView tableview, nint section)
            {
                return tabledata.Count;
            }

            public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
            {
                UIAlertController okAlertController = UIAlertController.Create("Call Number", tabledata[indexPath.Row].phoneNumber, UIAlertControllerStyle.Alert);
                okAlertController.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));
                owner.PresentViewController(okAlertController, true, null);

                tableView.DeselectRow(indexPath, true);
            }
        }
    }
}
